### ISSUE TITLE
Grabbing conversations outside of Roam?

### ISSUE THREAD

**Issue by JayThibs** [dvargas92495/roamjs-otter#10]
Hey, this repo is cool and I'd like to use it to eventually connect to Roam. 

However, I'd like to simply grab the conversations directly from my machine to extract the text. Is there some way you could direct me on how to do this? I tried the otter.ai-api repo (https://github.com/omerdn1/otter.ai-api/issues/22), but it isn't working and I fear it is because the website was updated so the code broke.

Your code is way more up-to-date so perhaps you've found a way around this? Honestly, this is my first day using javascript (I typically use Python) so it's hard for me to understand the codebase. Any ideas on what I can use to simply grab the conversations from otter? Thanks! :)

**Comment by dvargasfuertes** [comment]
Im not too familiar with Otter. Are conversations a subset of speeches or a different category altogether?

**Comment by JayThibs** [comment]
@dvargas92495 No, I mean speeches = conversations. It's just that Otter calls them "Conversations" and that repo I linked to calls them "Speeches". This may be because Otter "Conversations" used to be called "Speeches." Though not sure. Either way, I believe they are the same.

**Comment by dvargasfuertes** [comment]
oh then this is the core feature of the extension - check out the docs: https://roamjs.com/extensions/otter

**Comment by jmatthewpryor** [comment]
@dvargas92495 is there any magic hidden in the lambda hosted API that sits in front of the Otter API? ie. compared to the otter.ai-api codebase what did you have to do to fix authentication?

**Comment by jmatthewpryor** [comment]
All good - I found the code for the lambda and got it work
