### ISSUE TITLE
Investigate issues around auto importing

### ISSUE THREAD

**Issue by dvargasfuertes** [dvargas92495/roamjs-otter#11]
"auto-import doesn't seem to work - I don't see any errors, it just doesn't seem to run" - Vlad from Discord

May want to look into stability solutions for SmartBlocks, then abstract framework into roamjs-components for reuse here

**Comment by Stvad** [comment]
Any updates on this? 👀

**Comment by dvargasfuertes** [comment]
Moved it up the [RoamJS Backlog](https://github.com/users/dvargas92495/projects/2/views/1?pane=issue&itemId=19720250)

**Comment by mdroidian** [comment]
look into backend API, scheduled job

**Comment by mdroidian** [comment]
#17  should fix the default auto-import issue.  
But another issue will still remain for multiple imports: https://github.com/samepage-network/otter-samepage/issues/4
