### ISSUE TITLE
Cannot import if otter email is different than roamjs email

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roamjs-otter#15]
I believe the offending code is [here](https://github.com/samepage-network/otter-samepage/blob/c0c253b1151f648b8c53c99659d70deea7f46ce8/api/speeches/post.ts#L195):

`if (user.rawToken !== authToken || email !== authEmail) return undefined;`

If I enter the email that is tied to my Roam Account in the Otter Roam Depot settings `The email tied to your Otter account`, then I had no problem importing.

**Comment by dvargasfuertes** [comment]
At first this was intentional, but thinking more about it, we actually probably don't care about this check bc the user is sending their password anyway. Let's remove!

**Comment by mdroidian** [comment]
https://github.com/samepage-network/otter-samepage/pull/2
