### ISSUE TITLE
CORS error when trying to use the extension

### ISSUE THREAD

**Issue by Stvad** [dvargas92495/roamjs-otter#3]
When I try to use the extension - I get a loading indication for a bit and then it stops doing anything

![image](https://user-images.githubusercontent.com/81347/147483282-913763ef-e221-42f9-8c8a-14fca4d99194.png)

When I look in the browser console I see the following errors from it:
> Access to XMLHttpRequest at 'https://lambda.roamjs.com/otter' from origin 'https://roamresearch.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Btw, I'm curious - why does this extension need a backend vs doing a direct query to otter?

**Comment by dvargasfuertes** [comment]
The CORs error is a red herring - There's an actual 401 being thrown in the backend and not being correctly surfaced here. Just pushed a change to at lease surface it better

Usually these 401s are from not setting a password

**Comment by Stvad** [comment]
Oh, it seems that I used the wrong email 🙈.   

still curious about: 
> Btw, I'm curious - why does this extension need a backend vs doing a direct query to otter?

**Comment by dvargasfuertes** [comment]
ah sorry - it's because we are using an unofficial API that returns CORs headers expecting requests come from otter's frontend. The backend serves as a proxy

**Comment by Stvad** [comment]
ah, I see. kind of frustrating that running things from the page context poses these additional limitations =\
