### ISSUE TITLE
Add an ability to tag text entries with a relative date

### ISSUE THREAD

**Issue by Stvad** [dvargas92495/roamjs-otter#5]
I find it useful to tag things that need my attention with a certain date, so I can ensure that I processed the note properly. It'd be great if you could do that as one of the template substitutions. 

One way to do it would be to use `chrono-node` to resolve natural dates (as roam-toolkit and phonetoroam do). 

But I think also just having a few basic things like `{today}`, `{tomorrow}` can be a simple 80/20 solution

**Comment by dvargasfuertes** [comment]
Open to this idea! Don't have the bandwidth to implement this myself for this extension but am accepting PRs
